version: '2'

services:
  api:
    container_name: hangmanAPI
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/hangmanAPI
    working_dir: /hangmanAPI
    tty: true
    stdin_open: true

  redis:
    container_name: hangmanDB
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
